services:
    php-fpm:
        container_name: slotegrator-fpm
        build:
            context: ./infra/php
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./project:/var/www/html
        networks:
            - slotegrator-network

    nginx:
        container_name: slotegrator-nginx
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./project:/var/www/html
            - ./infra/nginx/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        networks:
            - slotegrator-network

    postgres:
        container_name: slotegrator-postgres
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: postgres12
            POSTGRES_DB: slotegrator
        ports:
            - "5432:5432"
        networks:
            - slotegrator-network

    selenium:
        container_name: slotegrator-selenium
        image: selenium/standalone-chrome:latest
        platform: linux/amd64
        ports:
            - "4444:4444"
        shm_size: "2g"
        networks:
            - slotegrator-network

networks:
    slotegrator-network:
        driver: bridge
